app:
  host: "0.0.0.0"
  port: 8042
  workers: 2  # Number of workers for uvicorn
  receive_timeout: 120  # Timeout for receiving audio bytes in seconds
  log_dir: logs

buffer:
  prefill_time: 375  # 375ms, decrease first chunk latency
  opus_frame_duration: 20  # 20ms, opus frame duration
  
realtime_vc:
  # 设备
  device: ["cuda:0"]  # 支持多卡，比如 ["cuda:0", "cuda:1"]
                                # 在多卡场景下，worker会循环依次部署到各个卡上
  is_debug: False  # 是否开启debug模式，debug模式会保存更多中间文件，便于排查问题

  # wav 相关
  reference_wav_path: "resources/refs/ref-24k.wav"  
  save_dir: "outputs/"  # save
  save_input: True  # is to save input wav
  save_output: True  # is to save output wav
  
  # realtime 
  SAMPLERATE_IN: 16000  # RealtimeVC模块输入采样率，从输入 到 vad, rmvpe, content encoder 都是16k
  SAMPLERATE_OUT: 22050   # vc模型输出采样率，一直延续到 Realtime_VC 模块的输出，会经过 rms-mixing 和 sola 
  BIT_DEPTH: 16  # 音频流的位深度，16位
  FRAMERATE: 50  # 帧率，代表系统的精度，和 content encoder的帧率一致； 1s 50帧，每帧20ms
                 # rvc:100（与其内部的f0 model一致）, seed-vc: 50（和content encoder一致）              
  
  # 上下文
  extra_time_ce: 4.5   # 留给 content encoder 上文额外时间，默认2.5s
  extra_time_dit: 1.5  # 留给 dit 上文额外时间，默认0.5s, 包含在extra_time_ce中，需要满足 extra_time_dit < extra_time_ce，
                       # content encoder 在得到 feat 后，会减去相对dit多出来的部分，再输入给 dit
  sola_buffer_time: 0.04  # sola算法做crossfade的区域，默认：0.04，不要超过 0.08; 会增加整体延迟
  block_time: 0.5  # 每块的时长，默认 0.5
  extra_time_right: 0.02  # 结尾的额外时间，默认: 0.02; 会增加整体延迟

  # auto_f0
  is_f0: False  # 是否使用自适应音高
  total_block_for_f0: 6  # 6； 用于计算中位数音高的总块数，只有探测到人声的才会包含，6块对应 3s
  
  # vc models
  diffusion_steps: 5  # 10；                    
  inference_cfg_rate: 0.7  # 0.7
  max_prompt_length: 5.0 # 3； 
  
  # rms_mix
  rms_mix_rate: 0.9   # 0.25； 这个参数是用来控制 RMS 混合的比例，
                      # 范围是 0 到 1。
                      # 0 表示完全使用 Input 的包络，1 表示完全使用 Infer 包络。 

  # sola
  is_sola: True  # 是否启用 SOLA 算法进行时域拼接                            

  # SLOW 监测
  send_slow_threshold: 100 # 100ms, 两个客户段发送过来的音频包之间的间隔，认定SLOW的阈值
                           # 一般客户端发送过来的音频包间隔是 20ms 或者 10ms
  recv_slow_threshold: 700 # 700ms，两个客户段收到服务端发送回去的音频包之间的时间间隔，认定SLOW的阈值
                           # 服务端发送回去的包，即 block_time，默认是500ms
  vc_slow_threshold: 300  # 从累计到一个chunk开始，到完成vc并推送给客户段之间的耗时，500ms一个chunk的话，
                          # 这里认为vc时间超过300就算SLOW


models:
  is_torch_compile: False  # use torch.compile to accelerate

  # retrieval
  is_retrieval: False  # 是否启用语义特征检索模块
  index_rate: 1.0  # # 检索特征相对权重，0.0 表示不使用检索特征，1.0 表示完全使用检索特征
  index_path: "resources/retrieval/ref-tencet-female__added_IVF256_Flat_nprobe_1.index"  # faiss索引文件路径
  
  # vad
  speech_noise_thres: 0.8  # VAD  语音与噪声能量比阈值 控制噪声过滤的灵敏度。vad默认0.6
  decibel_thres: -50  # 分贝阈值 低于该分贝的帧判为静音。vad默认-100.0

  # cfm
  t_span_schedule: "cosine"  # "linear", "cosine"， 线性 or 余弦重排，

  # 自定义模型路径，比如训练后的模型
  dit_checkpoint_path: null
  dit_config_path: null

  defalut_original_model: "tiny"  # "tiny", "small", "base"  
                                  # 如果没有指定自定义的模型路径：dit_checkpoint_path， dit_config_path。
                                  # 则使用seed-vc原始模型


